<?php
/**
 * MyArcadePlugin Default Categories
 *
 * @author Daniel Bakovic <contact@myarcadeplugin.com>
 * @copyright (c) 2015, Daniel Bakovic
 * @license http://myarcadeplugin.com
 * @package MyArcadePlugin/Modules/IBPArcadeScores
 * @version 5.0.0
 */

$feedcategories= array(

array ( 'Name' => "Action",
'ID' => 0,
'Slug' => "action",
'Kongregate' => true,
'Famobi' => "action,jump-and-run",
'FGD' => true,
'FOG' => false,
'Spilgames' => "Action,War",
'Scirra'  => true,
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Adventure",
'ID' => 1,
'Slug' => "adventure",
'Kongregate' => true,
'Famobi' => false,
'FGD' => true,
'FOG' => true,
'Spilgames' => true,
'Scirra'  => false,
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Arcade",
'ID' => 1,
'Slug' => "arcade",
'Kongregate' => false,
'Famobi' => true,
'FGD' => true,
'FOG' => false,
'Spilgames' => false,
'Scirra'  => false,
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Board Game",
'ID' => 3,
'Slug' => "boardgame",
'Kongregate' => false,
'Famobi' => 'cards,match-3',
'FGD' => false,
'FOG' => false,
'Spilgames' => 'Board and Card,Mahjong,Bubble Shooter,Match-3,Sudoku',
'Scirra'  => false,
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Casino",
'ID' => 4,
'Slug' => "casino",
'Kongregate' => false,
'Famobi' => false,
'FGD' => true,
'FOG' => false,
'Spilgames' => false,
'Scirra'  => false,
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Defense",
'ID' => 1,
'Slug' => "defense",
'Kongregate' => false,
'Famobi' => false,
'FGD' => true,
'FOG' => true,
'Spilgames' => false,
'Scirra'  => false,
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Customize",
'ID' => 5,
'Slug' => "customize",
'Kongregate' => false,
'Famobi' => "make-up",
'FGD' => false,
'FOG' => false,
'Spilgames' => 'Doll,Celebrity,Creation,Halloween,Kids,Painting',
'Scirra'  => false,
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Dress-Up",
'ID' => 6,
'Slug' => "dressup",
'Kongregate' => false,
'Famobi' => "dress-up,girls",
'FGD' => false,
'FOG' => false,
'Spilgames' => 'Dress Up,Girls,Kissing,Make Up,Makeover,Princess',
'Scirra'  => false,
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Driving",
'ID' => 7,
'Slug' => "driving",
'Kongregate' => false,
'Famobi' => "cars,racing",
'FGD' => true,
'FOG' => true,
'Spilgames' => 'Racing,Uphill Racing',
'Scirra'  => false,
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Education",
'ID' => 8,
'Slug' => "education",
'Kongregate' => false,
'Famobi' => false,
'FGD' => false,
'FOG' => false,
'Spilgames' => false,
'Scirra'  => false,
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Fighting",
'ID' => 10,
'Slug' => "fighting",
'Kongregate' => false,
'Famobi' => false,
'FGD' => true,
'FOG' => false,
'Spilgames' => false,
'Scirra'  => false,
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Jigsaw",
'ID' => 12,
'Slug' => "jigsaw",
'Kongregate' => false,
'Famobi' => false,
'FGD' => false,
'FOG' => false,
'Spilgames' => false,
'Scirra'  => false,
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Multiplayer",
'ID' => 14,
'Slug' => "multiplayer",
'Kongregate' => true,
'Famobi' => true,
'FGD' => true,
'FOG' => true,
'Spilgames' => false,
'Scirra'  => false,
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Other",
'ID' => 15,
'Slug' => "other",
'Kongregate' => false,
'Famobi' => "quiz,cooking",
'FGD' => true,
'FOG' => array ('Flying', '3D'),
'Spilgames' => 'Fun,Animal,Skill,Hidden Objects,Cooking,Platform,Seasonal',
'Scirra'  => true, /* Rotary */
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Puzzles",
'ID' => 16,
'Slug' => "puzzles",
'Kongregate' => true,
'Famobi' => true, /*Puzzle*/
'FGD' => true, /*Puzzle*/
'FOG' => true, /*Puzzle*/
'Spilgames' => 'Puzzle,Physics',
'Scirra'  => true,
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Rhythm",
'ID' => 17,
'Slug' => "rythm",
'Kongregate' => true,
'Famobi' => false,
'FGD' => true,
'FOG' => false,
'Spilgames' => "Music",
'Scirra'  => false,
'Status'  => "checked",
'Mapping' => "",
'Info' => "(Music on Kongregate)"),

array ( 'Name' => "Shooting",
'ID' => 18,
'Slug' => "shooting",
'Kongregate' => true,
'Famobi' => false,
'FGD' => true, /*Shooter*/
'FOG' => true,
'Spilgames' => true,
'Scirra'  => true, /*Shooter*/
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Sports",
'ID' => 20,
'Slug' => "sports",
'Kongregate' => true,
'Famobi' => true,
'FGD' => true,
'FOG' => true,
'Spilgames' => true,
'Scirra'  => false,
'Status'  => "checked",
'Mapping' => "",
'Info' => ""),

array ( 'Name' => "Strategy",
'ID' => 21,
'Slug' => "strategy",
'Kongregate' => true,
'Famobi' => "breakout,bubble-shooter",
'FGD' => true,
'FOG' => false,
'Spilgames' => 'Simulation,Tower Defense,Time Management,Social',
'Scirra'  => false,
'Status'  => "checked",
'Mapping' => "",
'Info' => "")
);
?>